# Generated by Django 5.1.2 on 2025-10-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zlecenia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numer', models.CharField(max_length=100)),
                ('zlecenie', models.CharField(blank=True, max_length=100, null=True)),
                ('towar', models.CharField(max_length=555)),
                ('ilosc', models.FloatField(blank=True, null=True)),
                ('cena', models.FloatField(blank=True, null=True)),
                ('osoba', models.CharField(blank=True, max_length=100, null=True)),
                ('data_zamowienia', models.DateField()),
                ('firma', models.CharField(blank=True, max_length=200, null=True)),
                ('data_przewodnika', models.DateField(blank=True, null=True)),
                ('data_oczekiwana', models.DateField(blank=True, null=True)),
                ('data_wprowadzenia', models.DateField(blank=True, null=True)),
                ('data_potwierdzona', models.DateField(blank=True, null=True)),
                ('data_otwarcia', models.DateField(blank=True, null=True)),
                ('data_zamkniecia', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'zlecenia',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('zamowienie', models.ForeignKey(db_column='zamowienie_id', on_delete=django.db.models.deletion.CASCADE, to='inz.zlecenia')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
