# Generated by Django 5.1.7 on 2025-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=100)),
                ('osoba', models.CharField(blank=True, max_length=100, null=True)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_zamowienia', models.DateField(blank=True, null=True)),
                ('data_oczekiwana', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Brak', max_length=50)),
            ],
        ),
    ]
