# Generated by Django 5.1.7 on 2025-10-12 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklisted_jwt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jwt_token', models.CharField(max_length=512, unique=True)),
                ('iat', models.BigIntegerField(default=1760259177.0219662)),
            ],
            options={
                'db_table': 'authjwt_blacklisted',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
            options={
                'db_table': 'authjwt_user',
            },
        ),
    ]
