# Generated by Django 5.1.2 on 2025-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisted_jwt',
            name='iat',
            field=models.BigIntegerField(default=1762369756),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
