# Generated by Django 5.1.7 on 2025-10-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisted_jwt',
            name='iat',
            field=models.BigIntegerField(default=1760259346.1009555),
        ),
    ]
