# Generated by Django 5.1.2 on 2025-11-05 19:30

from django.db import migrations, models

def create_default_admin(apps,schema_editor):
    User = apps.get_model('AuthJWT', 'User')
    if not User.objects.filter(username="admin").exists():
        User.objects.create(username="admin",password="admin123",email="admin@example.com",position="admin", role="admin" )

class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisted_jwt',
            name='iat',
            field=models.BigIntegerField(default=1762369756),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.RunPython(create_default_admin),
    ]
