# Generated by Django 5.1.2 on 2025-10-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
