# Generated by Django 5.1.2 on 2025-11-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0002_alter_blacklisted_jwt_iat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisted_jwt',
            name='iat',
            field=models.BigIntegerField(default=1762369297.1318436),
        ),
    ]
