# Generated by Django 5.1.2 on 2025-11-08 17:14

from django.db import migrations

def create_default_admin(apps,schema_editor): # funkcja na default admin
    User = apps.get_model('AuthJWT', 'User')
    if not User.objects.filter(username="admin").exists():
        User.objects.create(username="admin",password="admin123",email="admin@example.com",position="admin", role="admin" )

class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0002_alter_blacklisted_jwt_iat_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(create_default_admin), #tworzenie default admina 
    ]
