# Generated by Django 5.1.2 on 2025-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklisted_jwt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jwt_token', models.CharField(max_length=512, unique=True)),
                ('iat', models.BigIntegerField(default=1759869092.977422)),
            ],
            options={
                'db_table': 'authjwt_blacklisted',
            },
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AlterModelTable(
            name='user',
            table='authjwt_user',
        ),
    ]
