# Generated by Django 5.1.2 on 2025-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthJWT', '0005_blacklisted_jwt_delete_meta_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisted_jwt',
            name='iat',
            field=models.BigIntegerField(default=1759869186.677351),
        ),
        migrations.AlterField(
            model_name='blacklisted_jwt',
            name='jwt_token',
            field=models.TextField(max_length=512, unique=True),
        ),
    ]
