# Generated by Django 5.2.7 on 2025-10-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthJWT", "0006_alter_blacklisted_jwt_iat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
        migrations.AlterField(
            model_name="blacklisted_jwt",
            name="iat",
            field=models.BigIntegerField(default=1760195719.851195),
        ),
    ]
