# Generated by Django 5.2.7 on 2025-10-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthJWT", "0007_user_role_alter_blacklisted_jwt_iat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklisted_jwt",
            name="iat",
            field=models.BigIntegerField(default=1760195741.136979),
        ),
    ]
